### ISSUE TITLE
Params cannot be serialized properly

### ISSUE THREAD

**Issue by ALeafWolf** [unjs/ofetch#117]
Hello,
  I tried to use the $fetch from Nuxt 3. When I attempt this params:
```
skillGroups.value = await $fetch(" http://localhost:1338/api/skill-groups", {
    params: { 
      locale: "zh", 
      filters: {
        slot: {
          $in: [2]
        }
    } },
  });
```
I'm expect the parameter to be 
```
http://localhost:1338/api/skill-groups?locale=zh&filters[slot][$in][0]=2
```
I got
 ```
http://localhost:1338/api/skill-groups?locale=zh&filters=[object+Object]
```
I know using [qs library](https://github.com/ljharb/qs)'s `qs.stringify()` can serialize this params correctly, but not sure where to configure this library's way to serialize params.

**Comment by NozomuIkuta** [comment]
As far as I searched, it is expected that you got `filters=[object+Object]` because keys and values of URL query (= URL search params) is converted to strings.

[URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams) constructor accepts an "application/x-www-form-urlencoded" string or an object where keys and values are also "application/x-www-form-urlencoded".

For more details: [WHATWG specification](https://url.spec.whatwg.org/#interface-urlsearchparams)

So, `qs` library provides an extended feature to it, that is dealing with nested objects and square brackets in parsed string.

If you think qs-like parsing/stringifying should be supported, it would be a feature request to [`unjs/ufo`](https://github.com/unjs/ufo) rather than `ohmyfetch`, which actually handles URL parts internally.

**Comment by Isa3v** [comment]
I use the `onRequest` hook to get around the problem and serialize the query this:
```js
// import { stringify } from 'qs'
onRequest({ options }) {
    if (options.params) {
        let convertedOptions = new URLSearchParams(stringify(options.params));
        options.params = Object.fromEntries(convertedOptions);
    }
},
```

**Comment by pi0** [comment]
Serializing params object values by yourself to string is always the best way. Latest [ufo](https://github.com/unjs/ufo/pull/123) upgraded in ofetch has a basic JSON serializer now.

**Comment by Goryyn** [comment]
> Serializing params object values by yourself to string is always the best way. Latest [ufo](https://github.com/unjs/ufo/pull/123) upgraded in ofetch has a basic JSON serializer now.

How ? Can I have an example?

**Comment by Goryyn** [comment]
@pi0 How ? Can I have an example?

**Comment by kricsleo** [comment]
@Goryyn You can try this for now, for example:

```ts
import { ofetch } from 'ofetch'
import { stringify } from 'qs'

const myFetch = ofetch.create({
  onRequest(context) {
    if(context.options.query) {
      const searchParams = new URLSearchParams(stringify(context.options.query));
      context.options.query = Object.fromEntries(searchParams);
    }
  }
})

const result = await myFetch('https://echo.apifox.com/get', {
  // This `query` would be encoded as "?filter[include][0]=images&filter[include][1]=category&filter[include][2]=attributes"
  query: {
    filter: {
      include: ['images', 'category', 'attributes'] 
    }
  }
})

console.log('result', result)
```
