### ISSUE TITLE
Add an option to allow http errors

### ISSUE THREAD

**Issue by pi0** [unjs/ofetch#207]
ofetch by default throws an error if the response status code is any of http standard error codes (such as 50x). However there are situations that users prefer to always get it as a response. 

Currently, we provide a solution in docs (https://github.com/unjs/ofetch#%EF%B8%8F-handling-errors), to use `.error(err => err.data)`. However in wrapped contexts when user is not directly using `$fetch` context, it is impossible. (https://github.com/nuxt/nuxt/issues/18713).

A new option like `ignoreResponseError` would make it possible to opt-out from the feature.

**Comment by UriahLight** [comment]
This looks like a step in the right direction, but it still doesn't feel friendly to communicate with real REST APIs. Am I missing something obvious, but even with the PR, I don't see a way to get the HTTP status code unless it's explicitly returned by the API as a JSON field, or unless I hook into the interceptors (`onRequestSuccess`, `onRequestError`).  When building a web app that relies exclusively on data returned from a standard REST API on the backend, this makes parsing every request very tedious, since I can't just look at a status code of 200 to parse a correct response and everything else as an incorrect response. I have to check for the existence of fields or bloat the code with interceptors. What am I missing?

**Comment by sannajammeh** [comment]
> This looks like a step in the right direction, but it still doesn't feel friendly to communicate with real REST APIs. I may be missing something obvious (new to Nuxt/$fetch/ofetch), but even with the PR, I don't see a way to get the HTTP status code unless it's explicitly returned by the API as a JSON field, or unless I hook into the interceptors (`onResponse*`). When building a web app that relies exclusively on data returned from a standard REST API on the backend, this makes parsing every request very tedious, since I can't just look at a status code of 200 to parse a correct response and everything else as an incorrect response. I have to check for the existence of fields or bloat the code with interceptors. What am I missing?

You're missing this:

```ts

try {
  await ofetch(...)
} catch(e) {
  if(e instanceof FetchError) {
     console.log(e.statusCode);
  }
}
```
