### ISSUE TITLE
Nuxt3 use default options

### ISSUE THREAD

**Issue by ideafm** [unjs/ofetch#209]
Hi! Is it possible to create default/global options (like onRequest interceptor) in Nuxt3?

**Comment by NozomuIkuta** [comment]
[`create` method](https://github.com/unjs/ofetch#%EF%B8%8F-create-fetch-with-default-options) would be what you are looking for.

You can reuse the created fetcher in your app (e.g. exposing it via a composable).

**Comment by ideafm** [comment]
But it not replace global $fetch. I wish to use it both on a client and server side.

**Comment by NozomuIkuta** [comment]
As far as I see the Nuxt 3 code and docs, currently there doesn't seem to be such options to configure global behavior of `$fetch`.

https://github.com/nuxt/nuxt/blob/6d7be476a2caaf4683193b62d15ddee00bf27804/packages/nuxt/src/app/entry.ts#L16-L21

https://nuxt.com/docs/api/utils/dollarfetch#fetch

This issue could be a feature request for Nuxt 3 itself rather than ofetch.

@pi0 

Am I missing something?

**Comment by ideafm** [comment]
it seems not, thanks

**Comment by ideafm** [comment]
https://github.com/nuxt/nuxt/discussions/18988

**Comment by palfaro91** [comment]
@pi0 any update on this? Is this still not possible?

**Comment by pi0** [comment]
@palfaro91 You can create a new fetch instance using `$fetch.create({})` in utils. it is best way to have shared utils.

**Comment by ideafm** [comment]
@pi But Nuxt stuff is unavailable in this way, like UseNuxtApp, useRuntimeConfig and other

**Comment by pi0** [comment]
Nuxt upstream tracker/discussion: https://github.com/nuxt/nuxt/issues/14736
