### ISSUE TITLE
Timeout feature

### ISSUE THREAD

**Issue by birdlavv** [unjs/ofetch#21]
Timeout support (limiting the request execution time) would allow for snappy client-facing network timeout error messages if network connectivity drops.

**Comment by SebJansen** [comment]
My apologies for hijacking this issue, but presumably because of a timeout-related issue, I am surprisingly getting the following returned when making an API call (with 500ms delay, but not with another URL that responds in 20ms) on server-side (not in the browser/client-side) with ohmyfetch on Nuxt 3:

```javascript
{ "data": null, "pending": false, "error": null }
```

whereas on client side the request succeeds without problem with either the 500ms or the 20ms URL

does ohmyfetch abort requests when they take longer than a certain amount of time? 500ms is surely on the low-side, so I must be misunderstanding something, but there's no error message

**Comment by nathanchase** [comment]
Would very much like to see timeouts implemented - preferably with an exponential increase in timeout duration on subsequent retries. This is a much needed and essential feature coming from relying on it with axios.

**Comment by oleynikd** [comment]
`retryTimeout` would be great too

**Comment by gustavopch** [comment]
It could be implemented using with https://npm.im/async-retry or adapted directly from the code of https://github.com/tim-kos/node-retry to avoid adding a dependency.

**Comment by gustavopch** [comment]
It could be implemented using https://npm.im/async-retry or adapted directly from the source code of https://github.com/tim-kos/node-retry to avoid adding a dependency.

**Comment by Siddharth24Khera** [comment]
> +1, would be a very useful feature to have. Currently have to hack around to get this to work in nuxt

@rmcmk Can you share the workaround you are using in Nuxt.

**Comment by ananthachetan** [comment]
For anyone looking for this feature, the native fetch API has its own implementation which we can use.
https://github.com/whatwg/fetch/issues/951#issuecomment-1139487844

You could do 
`
$fetch("/api", {
            signal: AbortSignal.timeout(10000),
        });
`

OR 

`
ofetch.create({
    signal: AbortSignal.timeout(60000),
})
`

**Comment by danielcmm** [comment]
Very much needed!

**Comment by seth100** [comment]
Looking forward to having this implemented !

**Comment by pi0** [comment]
implemented in https://github.com/unjs/ofetch/pull/268 (finally!)
