### ISSUE TITLE
When using $fetch.raw, clone() cannot be used.

### ISSUE THREAD

**Issue by R-Az** [unjs/ofetch#404]
### Environment

node: v22.0.0
ofetch: 1.3.4

### Reproduction

This can be reproduced by adding the following test to test/index.test.ts.

```ts
it("raw available clone", async () => {
    const response = await $fetch.raw(getURL("ok"));
    const clone = response.clone();
    expect(clone.clone()).to.be.instanceOf(Response);
    expect(await response.text()).to.equal(await clone.text());
  })
```
error message
```
TypeError: Response.clone: Body has already been consumed.
```

### Describe the bug

The Response type returned by the browser's fetch function becomes unable to use clone() once the body or text methods have been called.
Consequently, if you want to use $fetch.raw('xxx').clone(), ofetch needs to internally call the body or text functions on a cloned instance.

Reference: https://developer.mozilla.org/en/docs/Web/API/Response/clone

### Additional context

I have a fix in mind, and I would like to submit a pull request if it is acceptable.

Also, I apologize if there were any inappropriate expressions in the English translation facilitated through ChatGPT.

**Comment by Aareksio** [comment]
This is by design.

---

It's the same as with https://github.com/unjs/ofetch/issues/405#issuecomment-2173568687, `.raw()` is reading the body for you. If you want to access the `response` object without reading the body, you must use `ofetch.native` or you can try with setting `responseType` to stream to avoid reading the body ([see source](https://github.com/unjs/ofetch/blob/main/src/fetch.ts#L187-L214)).

**Comment by R-Az** [comment]
Thank you.
I understand that it is by design.
I didn't realize that there was a workaround using responseType.
This workaround worked well in my project.

Sorry for taking up your time.
Thank you very much.
