### ISSUE TITLE
Add defaults headers to preconfigured instance

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/ofetch#431]
### Describe the feature

Hello 👋,

In framework like Nuxt, an ofetch instance is already available and used within the framework or modules (`$fetch`).

But sometimes, you need to add default headers to every request. It is not an option to create a custom ofetch instance https://nuxt.com/docs/guide/recipes/custom-usefetch since these headers must be used by both the framework request and the modules.

I try to overwrite the `$fetch` (https://github.com/nuxt/nuxt/issues/28620) but I really don't like this and I wondering if something like Axios (https://axios-http.com/docs/config_defaults) could be considered.

related to https://github.com/nuxt/nuxt/issues/28620

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
`$fetch` API is **intentionally** immutable and not allowing headers.

It is a feature by design -- just like standard fetch. You should use explicit wrapper utils that add global settings like headers.

---

The context for nuxt: it was a mistake in the legacy Nuxt axios module we allowed application-wide mutations.
